# Python Library

NumPy

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np

arr_1 = np.array([5, 9, 12, 11])
arr_2 = np.array([3, 9, 4, 8])

sum_arr = arr_1 + arr_2
print(sum_arr)


diff_arr = arr_1 - arr_2
print(diff_arr)

prod_arr = arr_1 * arr_2
print(prod_arr)

div_arr = arr_1 / arr_2
print(div_arr)

[ 8 18 16 19]
[2 0 8 3]
[15 81 48 88]
[1.66666667 1.         3.         1.375     ]


In [10]:
import numpy as np

arr =np.array([16, 9, 25, 64])
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

max_value = np.max(arr)
print(max_value)

min_value = np.min(arr)
print(min_value)

sum_value = np.sum(arr)
print(sum_value)

mean_value = np.mean(arr)
print(mean_value)

[4. 3. 5. 8.]
64
9
114
28.5


In [17]:
import numpy as np

arr_2d = np.array([[6, 8, 10], [7, 5, 8]])
print(arr_2d)

print(arr_2d.shape) # returns the dimensions of the array
print(arr_2d.ndim)  # returns the number of dimensions
print(arr_2d.size)  # returns the total number of elements

print("-----------------------------")

arr = np.array([5, 6, 9])
print(arr.shape)

[[ 6  8 10]
 [ 7  5  8]]
(2, 3)
2
6
-----------------------------
(3,)


In [1]:
import numpy as np
arr = np.array([[[5, 6],[9, 10],[12, 14]], 
                [[4, 6],[8, 7],[10, 12]], 
                [[15, 18],[21, 24],[27, 30]]])

print(arr)
print(arr.shape)
print(arr.ndim)

[[[ 5  6]
  [ 9 10]
  [12 14]]

 [[ 4  6]
  [ 8  7]
  [10 12]]

 [[15 18]
  [21 24]
  [27 30]]]
(3, 3, 2)
3


In [ ]:
import numpy as np

arr = np.array([[6, 4, 8], [9, 5, 8]])
print(arr[0][2]) # Not recommended it's slower, we use arr[row, column] in numpy
print(arr[0, 2])

8
8


In [ ]:
import numpy as np

arr = np.array([12, 18, 22, 19, 30])
condition = arr > 18
print(condition)

filtered_arr = arr[condition]
print(filtered_arr)

print(arr[arr > 18])

[False False  True  True  True]
[22 19 30]
[22 19 30]


In [40]:
arr = np.array([12, 18, 22, 19, 30])

print(arr[(arr > 15) & (arr < 20)])

[18 19]


In [44]:
arr = np.array([
    [12, 5, 7, 20],
    [3, 15, 8, 2],
    [10, 25, 6, 18],
    [4, 11, 30, 9]
])

# extract all elements that's one
# greater than 10 and less than 5
# And not equal to 5

print(arr[((arr > 10) | (arr < 5)) & (arr != 5)])

[12 20  3 15  2 25 18  4 11 30]


Array initialization

In [45]:
arr = np.zeros((3, 4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [46]:
import numpy as np

arr = np.full((2, 3), 7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [68]:
import numpy as np

arr = np.empty((2, 3)) # fill with garbage values
print(arr)

[[1.17034405e-311 1.17034405e-311 1.17034405e-311]
 [1.17030933e-311 0.00000000e+000 1.11253693e-308]]


Python pandas Library

In [90]:
import pandas as pd

data = {
    'Name': ['Shehan', 'Kaveen', 'Nimal', 'Kamal'],
    'Age': [22, 30, 35, 40]
}

df = pd.DataFrame(data)
print(df)

print("-----------------------")

print(df.loc[1])

print("-----------------------")

print(df.loc[2, "Age"]) # [row label, column label]

print("-----------------------")
print(df.iloc[3])

print("-----------------------")
print(df.iloc[3, 1])


     Name  Age
0  Shehan   22
1  Kaveen   30
2   Nimal   35
3   Kamal   40
-----------------------
Name    Kaveen
Age         30
Name: 1, dtype: object
-----------------------
35
-----------------------
Name    Kamal
Age        40
Name: 3, dtype: object
-----------------------
40


In [1]:
import pandas as pd

data = {
    'Name': ['Shehan', 'Kaveen', 'Nimal', 'Kamal'],
    'Age': [22, 30, 35, 40]
}

df = pd.DataFrame(data)

print(df['Name'])

0    Shehan
1    Kaveen
2     Nimal
3     Kamal
Name: Name, dtype: object


In [19]:
import pandas as pd

data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index=['day1', 'day2', 'day3'])
print(df)

print("-----------------------")
print(df.loc['day3'])
print(df.loc['day2', 'duration'])

print("----------------------------------")
print(df.shape)
print(df.size)

print("----------------------------------")
print(list(df.columns))

      calories  duration
day1       420        50
day2       380        40
day3       390        45
-----------------------
calories    390
duration     45
Name: day3, dtype: int64
40
----------------------------------
(3, 2)
6
----------------------------------
['calories', 'duration']


In [43]:
data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index=['day1', 'day2', 'day3'])
arr = df.values
print(arr)
print(type(arr)) # numpy.ndarray

print("-----------------------")
# print(df.loc[df.index[-1]])
print(df.iloc[-1])

print("-----------------------")
print(df)
print(len(df))
print(df.shape) #tuple (rows, columns)
print(df.shape[0]) # tuple accessing use indexing

[[420  50]
 [380  40]
 [390  45]]
<class 'numpy.ndarray'>
-----------------------
calories    390
duration     45
Name: day3, dtype: int64
-----------------------
      calories  duration
day1       420        50
day2       380        40
day3       390        45
3
(3, 2)
3


In [46]:
import pandas as pd

data = {
    "calories": [420, 380, 390, 450],
    "duration": [50, 40, 45, 60]
}

df = pd.DataFrame(data, index=['day1', 'day2', 'day3', 'day4'])

print(df.sum())
print(df.mean())
print(df.describe())

calories    1640
duration     195
dtype: int64
calories    410.00
duration     48.75
dtype: float64
         calories   duration
count    4.000000   4.000000
mean   410.000000  48.750000
std     31.622777   8.539126
min    380.000000  40.000000
25%    387.500000  43.750000
50%    405.000000  47.500000
75%    427.500000  52.500000
max    450.000000  60.000000


In [56]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Shehan", "Kaveen", "Nimal", "Kamal", "Ravi"],
    "Age": [22, 18, 35, 16, 28],
    "Salary": [50000, 60000, 55000, 70000, 52000],
    "City": ["Colombo", "Kandy", "Galle", "Jaffna", "Matara"]
})

print(df)

filtered_df = df[df['Age'] > 19]
print(filtered_df)

print("---------------------------------")
# Age greater than 20 and Salary greater than 50000

filtered_df = df[(df['Age'] > 20) & (df['Salary'] > 50000)]
print(filtered_df)

     Name  Age  Salary     City
0  Shehan   22   50000  Colombo
1  Kaveen   18   60000    Kandy
2   Nimal   35   55000    Galle
3   Kamal   16   70000   Jaffna
4    Ravi   28   52000   Matara
     Name  Age  Salary     City
0  Shehan   22   50000  Colombo
2   Nimal   35   55000    Galle
4    Ravi   28   52000   Matara
---------------------------------
    Name  Age  Salary    City
2  Nimal   35   55000   Galle
4   Ravi   28   52000  Matara


In [57]:
# How to add a new column

import pandas as pd

df = pd.DataFrame({
    "Name": ["Shehan", "Kaveen", "Nimal", "Kamal", "Ravi"],
    "Age": [22, 18, 35, 16, 28],
    "Salary": [50000, 60000, 55000, 70000, 52000],
    "City": ["Colombo", "Kandy", "Galle", "Jaffna", "Matara"]
})

print(df)

df['Employee ID'] = [101, 102, 103, 104, 105]
print(df)

     Name  Age  Salary     City
0  Shehan   22   50000  Colombo
1  Kaveen   18   60000    Kandy
2   Nimal   35   55000    Galle
3   Kamal   16   70000   Jaffna
4    Ravi   28   52000   Matara
     Name  Age  Salary     City  Employee ID
0  Shehan   22   50000  Colombo          101
1  Kaveen   18   60000    Kandy          102
2   Nimal   35   55000    Galle          103
3   Kamal   16   70000   Jaffna          104
4    Ravi   28   52000   Matara          105


You are given flowing the pandas data frame containing product seles

df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
    "UnitSold": [15, 50, 34, 20, 40],
    "Price": [12000, 1500, 3500, 25000, 6000],
    "Discount": [0.10, 0.05, 0.08, 0.12, 0.07]
})

* Calculate the final price after discount for each product
* Calculate the total revenue for each product after discount
* For above part 1 and part 2 you should add both result as new coloms to the dataframe
* Filter and Display the the product where revenue is grater that 500,000
* Calculate the total revenue of all product combined

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Headset"],
    "UnitSold": [12, 50, 34, 20, 40],
    "Price": [120000, 1500, 3500, 25000, 6000],
    "Discount": [0.10, 0.05, 0.08, 0.12, 0.07]
})

df["Final Price"] = df["Price"] - (df["Price"] * df["Discount"])
df["Total Revenue"] = df["Final Price"] * df["UnitSold"]
print(df)

filtered_df = df[df["Total Revenue"] > 500000]
print(filtered_df)

total_revenue = df["Total Revenue"].sum()
print(total_revenue)


    Product  UnitSold   Price  Discount  Final Price  Total Revenue
0    Laptop        12  120000      0.10     108000.0      1296000.0
1     Mouse        50    1500      0.05       1425.0        71250.0
2  Keyboard        34    3500      0.08       3220.0       109480.0
3   Monitor        20   25000      0.12      22000.0       440000.0
4   Headset        40    6000      0.07       5580.0       223200.0
  Product  UnitSold   Price  Discount  Final Price  Total Revenue
0  Laptop        12  120000       0.1     108000.0      1296000.0
2139930.0


In [ ]:
import pandas as pd

data = {
    "Name": ["Shehan", "Kaveen", "Nimal"],
    "Age": [22, 30, 35],
}

df = pd.DataFrame(data)
df.loc[len(df)] = ["Kamal", 28]
print(df)

df = df.drop("Age", axis=1) # drop row use axis=0 and drop column use axis=1
print(df)

     Name  Age
0  Shehan   22
1  Kaveen   30
2   Nimal   35
3   Kamal   28
     Name
0  Shehan
1  Kaveen
2   Nimal
3   Kamal


Read CSV Files

In [4]:
import pandas as pd

df = pd.read_csv('person_data.csv')
print(df.head())

   Name  Age    Country      City
0  Alex   16  Sri Lanka   Colombo
1   Mia   17  Australia    Sydney
2  Ravi   15        USA  New York
3  Sara   16         UK    London
4  Liam   17     Canada   Toronto


In [14]:
import pandas as pd

df = pd.read_json('my_json.json', lines=True)
print(df)

     Name  Age     City
0  Shehan   22  Colombo
